spring:
  datasource:
    url: jdbc:postgresql://localhost:8002/liquibase
    username: liquibase
    password: liquibase
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
